import { cn } from "@/lib/utils"

interface Signal {
  bracket: string
  side: string
  edge: number
  model_prob: number
  market_price: number
  kelly_pct: number
  approved: boolean
  created_at: string
}

export function SignalsTable({ signals }: { signals: Signal[] }) {
  return (
    <div className="rounded-lg border border-border bg-card">
      <div className="border-b border-border px-6 py-4">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
          Recent Signals ({signals.length})
        </h2>
        <p className="mt-1 mb-3 text-xs text-muted-foreground">Trade signals generated by the 4-model ensemble. Each signal shows the model's probability vs the market price, the edge (difference), and the Kelly-sized bet amount.</p>
      </div>
      {signals.length > 0 ? (
        <div className="max-h-[400px] overflow-y-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border text-xs text-muted-foreground">
                <th className="px-6 py-2 text-left">Status</th>
                <th className="px-6 py-2 text-left">Bracket</th>
                <th className="px-6 py-2 text-left">Model</th>
                <th className="px-6 py-2 text-right">Ensemble Prob</th>
                <th className="px-6 py-2 text-right">Market Price</th>
                <th className="px-6 py-2 text-right">Edge</th>
                <th className="px-6 py-2 text-right">Kelly %</th>
              </tr>
            </thead>
            <tbody>
              {signals.map((s, i) => (
                <tr key={i} className="border-b border-border last:border-0 hover:bg-accent/50">
                  <td className="px-6 py-2.5">
                    <span className={`h-2 w-2 inline-block rounded-full ${s.approved ? "bg-success" : "bg-muted-foreground"}`} />
                    <span className="ml-2 text-xs">{s.approved ? "Executed" : "Pending"}</span>
                  </td>
                  <td className="px-6 py-2.5 font-medium">{s.bracket}</td>
                  <td className="px-6 py-2.5">
                    <span className="rounded bg-muted px-1.5 py-0.5 text-xs">4-Model Ensemble</span>
                  </td>
                  <td className="px-6 py-2.5 text-right">{(s.model_prob * 100).toFixed(1)}%</td>
                  <td className="px-6 py-2.5 text-right">{(s.market_price * 100).toFixed(1)}%</td>
                  <td className={cn("px-6 py-2.5 text-right font-medium", s.edge > 0.05 ? "text-success" : "text-muted-foreground")}>
                    +{(s.edge * 100).toFixed(1)}%
                  </td>
                  <td className="px-6 py-2.5 text-right">{(s.kelly_pct * 100).toFixed(2)}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <p className="px-6 py-8 text-center text-sm text-muted-foreground">No signals for this module yet</p>
      )}
    </div>
  )
}
